name: SFTP Deploy

on:
  push:
    branches:
      - master  # деплой при пуше в master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Upload files to server via SFTP
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: 22
          source: |
            ./               # заливаем всё из корня проекта
            !.git/**         # исключаем папку .git
            !.github/**      # исключаем workflows и прочее
            !node_modules/** # исключаем зависимости
            !.env            # не отправляем конфигурации
            !README.md
            !*.yml
          target: /var/www/chatpwa.ru
