name: Auto Deploy via SSH

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Upload files via SCP (SFTP)
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          port: 22
          source: ./
          exclude: |
            .git/
            .github/
            node_modules/
            web/node_modules/
          target: /var/www/chatpwa.ru

      - name: Build project on remote server
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          port: 22
          script: |
            cd /var/www/chatpwa.ru/web
            npm install --legacy-peer-deps
            npm run build

